// <auto-generated />

using MainApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MainApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250614135140_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticlesArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("integer");

                    b.HasKey("ArticlesArticleId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("ArticleTag");

                    b.HasData(
                        new
                        {
                            ArticlesArticleId = 1,
                            TagsTagId = 3
                        },
                        new
                        {
                            ArticlesArticleId = 1,
                            TagsTagId = 2
                        },
                        new
                        {
                            ArticlesArticleId = 2,
                            TagsTagId = 3
                        },
                        new
                        {
                            ArticlesArticleId = 2,
                            TagsTagId = 1
                        },
                        new
                        {
                            ArticlesArticleId = 3,
                            TagsTagId = 2
                        },
                        new
                        {
                            ArticlesArticleId = 3,
                            TagsTagId = 1
                        },
                        new
                        {
                            ArticlesArticleId = 4,
                            TagsTagId = 2
                        },
                        new
                        {
                            ArticlesArticleId = 4,
                            TagsTagId = 3
                        },
                        new
                        {
                            ArticlesArticleId = 5,
                            TagsTagId = 3
                        },
                        new
                        {
                            ArticlesArticleId = 5,
                            TagsTagId = 2
                        });
                });

            modelBuilder.Entity("MainApi.Models.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("Visibility")
                        .HasColumnType("boolean");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            CategoryId = 1,
                            Description = "Adipisci nobis aperiam facere beatae quisquam tempore non tempore. Rerum ipsa eos vero corrupti enim veritatis ducimus cum autem. Quibusdam omnis ducimus vero dolor. Officiis et adipisci quis suscipit debitis accusamus accusamus voluptatem modi. Esse facere et similique itaque recusandae qui minus.",
                            Name = "Sequi velit rem sit reiciendis id et commodi.",
                            UserId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 2,
                            CategoryId = 2,
                            Description = "Cum error ut impedit nulla occaecati. Odio accusamus voluptatem quo non. Ipsam fugit rerum quibusdam alias provident nesciunt voluptate est. Atque neque modi tempora aut ea et sint aperiam. Debitis perferendis nulla qui. Corrupti delectus dolor molestias.",
                            Name = "Et et aliquid rerum fuga rem aut voluptatum dolores ut.",
                            UserId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 3,
                            CategoryId = 1,
                            Description = "Et aut non ut perspiciatis eligendi nihil sed eum. Inventore velit nulla dicta alias velit. Ea itaque voluptatem perspiciatis beatae.",
                            Name = "Sed qui exercitationem aut doloribus.",
                            UserId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 4,
                            CategoryId = 2,
                            Description = "Eveniet ipsa delectus ut adipisci alias qui est ab minus. Sint rerum voluptatibus hic harum voluptatem eum. Repellendus velit mollitia vel qui repellat id ab suscipit.",
                            Name = "Molestiae dolores aut veritatis tenetur necessitatibus velit voluptas.",
                            UserId = 1,
                            Visibility = true
                        },
                        new
                        {
                            ArticleId = 5,
                            CategoryId = 1,
                            Description = "Veritatis aut et nobis rerum amet ea magni est est. Nisi odio velit necessitatibus. Quia voluptatem et quia quisquam voluptatem delectus eum magni consequuntur. Enim rem rerum neque ut voluptatibus voluptates non labore expedita. Et soluta ratione cumque error ut est nostrum facere.",
                            Name = "Minus eaque ipsa autem.",
                            UserId = 1,
                            Visibility = true
                        });
                });

            modelBuilder.Entity("MainApi.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Technology articles",
                            CategoryName = "Tech",
                            UserId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Lifestyle articles",
                            CategoryName = "Life",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MainApi.Models.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Title = "C#"
                        },
                        new
                        {
                            TagId = 2,
                            Title = "Blazor"
                        },
                        new
                        {
                            TagId = 3,
                            Title = "AI"
                        });
                });

            modelBuilder.Entity("MainApi.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Deleted = false,
                            UserName = "mittie_johnston"
                        });
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("MainApi.Models.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainApi.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainApi.Models.Entities.Article", b =>
                {
                    b.HasOne("MainApi.Models.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainApi.Models.Entities.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainApi.Models.Entities.Category", b =>
                {
                    b.HasOne("MainApi.Models.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainApi.Models.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("MainApi.Models.Entities.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
